### ISSUE TITLE
OpenSUSE Python 3.8 运行错误。

### ISSUE THREAD

**Issue by OrvilleQ** [rickyhoho/cpu_temp#1]
```
[MCDR] [20:07:36] [TaskExecutor/ERROR]: Error when executing command "!!temp show" with command source "Player OrwillQSong" on Literal[literals={'!!temp'}] registered by cpu_temp@2.5.2-cn
Traceback (most recent call last):
  File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/command_manager.py", line 58, in execute_command
    node.execute(source, command)
  File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 244, in execute
    self._execute(source, command, command, {})
  File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 215, in _execute
    child_literal._execute(source, command, trimmed_remaining, context)
  File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 196, in _execute
    self.__smart_callback(self.callback, source, context)
  File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 159, in __smart_callback
    return callback(*args[:spec_args_len])
  File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 329, in <lambda>
    runs(lambda src : task.cal_temp(1, src))
  File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 196, in cal_temp
    avg_temp = self.avg_temp(num, temp, src)
  File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 177, in avg_temp
    for i in range(0, len(temp['coretemp'])):
KeyError: 'coretemp'
```

**Comment by R1ckyH** [comment]
> ```
> [MCDR] [20:07:36] [TaskExecutor/ERROR]: Error when executing command "!!temp show" with command source "Player OrwillQSong" on Literal[literals={'!!temp'}] registered by cpu_temp@2.5.2-cn
> Traceback (most recent call last):
>   File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/command_manager.py", line 58, in execute_command
>     node.execute(source, command)
>   File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 244, in execute
>     self._execute(source, command, command, {})
>   File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 215, in _execute
>     child_literal._execute(source, command, trimmed_remaining, context)
>   File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 196, in _execute
>     self.__smart_callback(self.callback, source, context)
>   File "/home/orwill/.local/lib/python3.8/site-packages/mcdreforged/command/builder/command_node.py", line 159, in __smart_callback
>     return callback(*args[:spec_args_len])
>   File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 329, in <lambda>
>     runs(lambda src : task.cal_temp(1, src))
>   File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 196, in cal_temp
>     avg_temp = self.avg_temp(num, temp, src)
>   File "/home/orwill/TSFF-Server/Survival/plugins/cpu_temp.py", line 177, in avg_temp
>     for i in range(0, len(temp['coretemp'])):
> KeyError: 'coretemp'
> ```

抱歉，我手头上没有能够直接获取传感器信息的OpenSUSE系统，请联系 qq 836650357 或从MCDR群里面找我处理问题
